name: CoswayUtil
version: '${version}'
main: CoswayUtil.CoswayUtil
description: "utility plugin for Cosway servers, a yescraft network server"
api-version: '1.21'
author: "Newt_00"
depend: [Vault]
authors:
  - Newt_00
website: "ycs.Newt-Tech.com"
commands:
  mage:
    description: Unsafe enchantment command
    usage: /mage <enchantment> <level>
    permission: coswayutil.mage
  scale:
    permission: cosway.scale
    usage: "/scale <float>"
  throw:
    description: Throws nearest player in a 10 block radius of you
    usage: "/throw"
    permission: cosway.throw
  gravitygauntlet:
    description: "Gives the player a Gravity Gauntlet"
    usage: "/gravitygauntlet"
    permission: CoswayUtil.GravityGauntlet
  getwand:
    description: "Gives player a levitation wand"
    usage: "/getwand"
    permission: CoswayUtil.wand
  launchstick:
    description: "give player a stick to use for launching themselves"
    usage: "/launchstick"
    permission: CoswayUtil.launchStick
  rapidbow:
    description: "gives player a rapid fire bow"
    usage: "/rapidbow"
    permission: CoswayUtil.rapidBow
  shopbook:
    description: "gives player shop book"
    usage: "/shopbook"
    permission: CoswayUtil.shop
  blockshop:
    description: "opens block shop"
    usage: "/blockshop"
    permission: CoswayUtil.shop
  writecheck:
    description: Writes a check to another player.
    usage: /writecheck <player> <amount>
  cashcheck:
    description: Cash a check you are holding.
    usage: /cashcheck
  unbreakable:
    description: Make the held tool unbreakable
    usage: /unbreakable
    permission: coswayutil.unbreakable
  repair:
    description: Repair the held tool
    usage: /repair
    permission: coswayutil.repair
  coswaysetpdc:
    description: Set a PDC string on a player
    usage: /coswaysetpdc <@s|player> <key> <value>
    permission: coswayutil.pdc.set
    permission-message: "&cYou don't have permission to use this."
  coswaygetpdc:
    description: Get a PDC string on a player
    usage: /coswaygetpdc <@s|player> <key>
    permission: coswayutil.pdc.get
    permission-message: "&cYou don't have permission to use this."
  givetreasurefountain:
    description: give player treasure fountain item
    usage: /givetreasurefountain
    permission: coswayutil.admin
    permission-message: "&cYou don't have permission to use this."
  shockwavebow:
    description: Give yourself the Shockwave Bow
    usage: /shockwavebow
    permission: coswayutil.op
  tpp:
    description: Teleport one player to another player
    usage: /tpp <player> <to player>
    permission: coswayutil.tpp
  rename:
    description: Rename held item
    usage: /rename <name>
    permission: coswayutil.rename
  coswayreload:
    description: Reload CoswayUtil configuration
    usage: /coswayreload
    permission: coswayutil.reload
  jail:
    description: Manually jail a player
    usage: /jail <player> <fine> <time>
  unjail:
    description: Release a player from jail
    usage: /unjail <player>
  placemagmafurnace:
    description: place a magma furnace
    usage: /placemagmafurnace
    permission: cosway.place
  dummy:
    description: Creates a player skin mannequin
    usage: /dummy <username|uuid>
    permission: coswayutil.dummy
  equip:
    description: Opens mannequin equipment
    usage: /equip
    permission: coswayutil.equip
  dummysettings:
    description: Change dummy settings
    usage: /dummysettings <setting> <value>
    permission: coswayutil.dummysettings
permissions:
  cosway.place:
    default: op
  coswayutil.mage:
    default: op
  coswayutil.tpp:
    default: op
  coswayutil.seen:
    description: Gives glowing effect
    default: op
  coswayutil.rename:
    default: op
  coswayutil.reload:
    default: op
  coswayutil.jail:
    default: op
  coswayutil.unjail:
    default: op