name: CoswayUtil
version: '${version}'
main: CoswayUtil.CoswayUtil
description: "utility plugin for Cosway servers, a yescraft network server"
api-version: '1.21'
author: "Newt_00"
website: "ycs.Newt-Tech.com"
commands:
  scale:
    permission: cosway.scale
    usage: "/scale <float>"
  throw:
    description: Throws nearest player in a 10 block radius of you
    usage: "/throw"
    permission: cosway.throw
  gravitygauntlet:
    description: "Gives the player a Gravity Gauntlet"
    usage: "/gravitygauntlet"
    permission: CoswayUtil.GravityGauntlet
  getwand:
    description: "Gives player a levitation wand"
    usage: "/getwand"
    permission: CoswayUtil.wand
  launchstick:
    description: give player a stick to use for launching themselves
    usage: /launchstick
    permission: CoswayUtil.launchStick
  rapidbow:
    description: gives player a rapid fire bow
    usage: /rapidbow
    permission: CoswayUtil.rapidBow