CoswayUtilname: CoswayUtil
version: '1.3-BETA'
main: CoswayUtil.CoswayUtil
description: "utility plugin for Cosway servers, a yescraft network server"
api-version: '1.21'
author: "Newt_00"
website: "ycs.Newt-Tech.com"
commands:
  scale:
    permission: cosway.admin
    usage: "/scale <float>"